<?php
require 'lib/model/om/BaseAircraftTypePeer.php';

/**
 * Skeleton subclass for performing query and update operations on the 'aircraft_type' table.
 *
 * AircraftType
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Jun 4 15:26:31 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements. This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package lib.model
 */
class AircraftTypePeer extends BaseAircraftTypePeer {
	static public function getAircraftTypeByName($name) {
		$criteria = new Criteria ();
		$criteria->add ( self::name, $name );
		return AircraftPeer::doSelectOne ( $criteria );
	}
	static public function GetBoeingLimits(){
		$c = new Criteria();
		$c->add(self::NAME, "B737_300", Criteria::EQUAL);
		$acType = self::doSelectOne($c);
		return $acType;
	}
	
	static public function GetAirbusLimits(){
		$c = new Criteria();
		$c->add(self::NAME, "A320_100", Criteria::EQUAL);
		$acType = self::doSelectOne($c);
		return $acType;
	}
	
	static public function GetAircaftType(Aircraft $aircaft){		
		$name = $aircaft->getAircraftType()->getName();
		
		if($name[0] == "B"){
			return Ac_Type::Boeing;
		}
		elseif($name[0] == 'A'){
			return  Ac_Type::Airbus;
		}
		return null;
	}
	
	static  public function getAircraftTypeByHlcId($hlcId) {
		$criteria = new Criteria ();
		$criteria->add ( AircraftTypePeer::HLC_ID, $hlcId );
		return  AircraftTypePeer::doSelectOne ( $criteria );
	}
	
	static  public function updateAircraftType($data) {
		$connection = Propel::getConnection ();
		
		if($data['angleType'] == 'long' && $data['forceType'] == 'f'){			
			$query = 'UPDATE `aircraft_type` SET `long_fatigue_limit_value` = ' . $data['value'] . ' WHERE `name` LIKE ' . "'". $data['aricaftType']. '%'. "'";			
		}
		
		if($data['angleType'] == 'long' && $data['forceType'] == 's'){
			$query = 'UPDATE `aircraft_type` SET `long_static_limit_value` = ' . $data['value'] . ' WHERE `name` LIKE ' . "'". $data['aricaftType']. '%'. "'";
		}
		
		if($data['angleType'] == 'lat' && $data['forceType'] == 's'){
			$query = 'UPDATE `aircraft_type` SET `lat_static_limit_value` = ' . $data['value'] . ' WHERE `name` LIKE ' . "'". $data['aricaftType']. '%'. "'";
		}
		
		$statement = $connection->prepare ( $query );
		$statement->execute ();		 
	}
} // AircraftTypePeer


abstract class Ac_Type{
	const Airbus = 'Airbus';
	const Boeing = 'Boeing';
}
