<?php
require 'lib/model/om/BaseAircraft.php';

/**
 * Skeleton subclass for representing a row from the 'aircraft' table.
 *
 * Aircraft
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed May 29 15:57:47 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements. This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package lib.model
 */
class Aircraft extends BaseAircraft {
} // Aircraft
