<?php
require 'lib/model/om/BaseAircraftType.php';

/**
 * Skeleton subclass for representing a row from the 'aircraft_type' table.
 *
 * AircraftType
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Jun 4 15:26:31 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements. This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package lib.model
 */
class AircraftType extends BaseAircraftType {
	
} // AircraftType
