<?php
require 'lib/model/om/BaseAircraftTypePeer.php';

/**
 * Skeleton subclass for performing query and update operations on the 'aircraft_type' table.
 *
 * AircraftType
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Jun 4 15:26:31 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements. This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package lib.model
 */
class AircraftTypePeer extends BaseAircraftTypePeer {
	static public function GetBoeingLimits(){
		$c = new Criteria();
		$c->add(self::NAME, "B737_300", Criteria::EQUAL);
		$acType = self::doSelectOne($c);
		return $acType;
	}
	
	static public function GetAirbusLimits(){
		$c = new Criteria();
		$c->add(self::NAME, "A320_100", Criteria::EQUAL);
		$acType = self::doSelectOne($c);
		return $acType;
	}
} // AircraftTypePeer
