<?php
require 'lib/model/om/BaseAircraftPeer.php';

/**
 * Skeleton subclass for performing query and update operations on the 'aircraft' table.
 *
 * Aircraft
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed May 29 15:57:47 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements. This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package lib.model
 */
class AircraftPeer extends BaseAircraftPeer {
	static public function GetTailNumbers() {
		$c = new Criteria ();
		$c->clearSelectColumns ();
		$c->setDistinct ();
		$c->addSelectColumn ( self::TAIL_NUMBER );
		$rs = self::doSelectStmt ( $c );
		$results = array ();
		
		while ( $row = $rs->fetch ( PDO::FETCH_BOTH ) ) {
			$results [] = $row ['TAIL_NUMBER'];
		}
		
		return $results;
	}
	static public function getAircraft($tail_number, AircraftType $aircraftType) {
		
		// TODO - get from rtc
		$criteria = new Criteria ();
		$criteria->add ( AircraftPeer::TAIL_NUMBER, $tail_number );
		$aircraft = AircraftPeer::doSelectOne ( $criteria );
		
		if ($aircraft == null) {			
			$aircraft = new Aircraft ();			
			$aircraft->setTailNumber ( $tail_number );
			$aircraft->setTypeId ( $aircraftType->getId () );			
			$aircraft->save ();
		}
		
		return $aircraft;
	}
	
	static public function getAircraftByTailNumber($tail_number) {	 
		$criteria = new Criteria ();
		$criteria->add ( AircraftPeer::TAIL_NUMBER, $tail_number );
		$aircraft = AircraftPeer::doSelectOne ( $criteria );
		return $aircraft;
	}
} // AircraftPeer
