<?php
/**
 * Skeleton subclass for representing a row from the 'auth_benutzer_modul' table.
 *
 * N x M Verbindungen von Benutzern und Modulen
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Sun Feb 14 14:53:15 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Benutzer_Modul extends BaseBenutzer_Modul {
}
