<?php
require 'lib/model/om/BaseDusFlugzeugkategorieAusnahmeRegistrierung.php';

/**
 * Skeleton subclass for representing a row from the 'dus_flugzeugkategorie_ausnahme_registrierung' table.
 *
 * Ausnahmeregel für einzelne Flugzeugregistrierungen
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sun May 5 18:10:47 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements. This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package lib.model
 */
class DusFlugzeugkategorieAusnahmeRegistrierung extends BaseDusFlugzeugkategorieAusnahmeRegistrierung {
} // DusFlugzeugkategorieAusnahmeRegistrierung
