<?php
require 'lib/model/om/BaseExceedEventPeer.php';

/**
 * Skeleton subclass for performing query and update operations on the 'exceed_event' table.
 *
 * ExceedEvent
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Sep 11 13:10:29 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements. This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package lib.model
 */
class ExceedEventPeer extends BaseExceedEventPeer {
} // ExceedEventPeer
