<?php
require 'lib/model/om/BaseFlugzeugzuordnungPeer.php';

/**
 * Skeleton subclass for performing query and update operations on the 'flugzeugzuordnung' table.
 *
 * Setzt Flugzeug mit dessen Airline und Flugzeugtyp zueinander in Beziehung
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sun May 5 18:10:47 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements. This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package lib.model
 */
class FlugzeugzuordnungPeer extends BaseFlugzeugzuordnungPeer {
} // FlugzeugzuordnungPeer
