<?php
require 'lib/model/om/BaseGruppe_WerkstattkundePeer.php';

/**
 * Skeleton subclass for performing query and update operations on the 'auth_gruppe_werkstattkunde' table.
 *
 * N X M Verbindungen von Gruppen und Kunden des Bereichs Werkstatt-Kunde
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Nov 26 13:57:34 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements. This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package lib.model
 */
class Gruppe_WerkstattkundePeer extends BaseGruppe_WerkstattkundePeer {
} // Gruppe_WerkstattkundePeer
