<?php
/**
 * Skeleton subclass for representing a row from the 'system_hilfe' table.
 *
 * Tabelle mit den Hilfeseiten
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Mon Mar 16 15:50:24 2009
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Hilfe extends BaseHilfe {
}
