<?php
require 'lib/model/om/BaseModul.php';

/**
 * Skeleton subclass for representing a row from the 'auth_modul' table.
 *
 * Hier sind alle Module von Legos aufgelistet
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sun May 5 18:10:45 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements. This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package lib.model
 */
class Modul extends BaseModul {
} // Modul
