<?php
require 'lib/model/om/BaseTaxibotMission.php';

/**
 * Skeleton subclass for representing a row from the 'taxibot_mission' table.
 *
 * TaxibotMission
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Jun 4 11:11:50 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements. This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package lib.model
 */
class TaxibotMission extends BaseTaxibotMission {
	
	public function GetTextFlightNumber($char1, $char2, $char3, $char4,$char5 ,$char6 ,$char7 ,$char8 )
	{
		$textFlightNumber = chr($char1);
		
		if ($char2 == 0){
			return  $textFlightNumber;
		}
		$textFlightNumber = $textFlightNumber . chr($char2);
		
		if ($char3 == 0){
			return  $textFlightNumber;
		}
		$textFlightNumber = $textFlightNumber . chr($char3);
		
		if ($char4 == 0){
			return  $textFlightNumber;
		}
		$textFlightNumber = $textFlightNumber . chr($char4);
		
		if ($char5 == 0){
			return  $textFlightNumber;
		}
		$textFlightNumber = $textFlightNumber . chr($char5);
		
		if ($char6 == 0){
			return  $textFlightNumber;
		}
		$textFlightNumber = $textFlightNumber . chr($char6);
		
		if ($char7 == 0){
			return  $textFlightNumber;
		}
		$textFlightNumber = $textFlightNumber . chr($char7);
		
		if ($char8 == 0){
			return  $textFlightNumber;
		}
		$textFlightNumber = $textFlightNumber . chr($char8);

		return $textFlightNumber;
	}  
	
	public function GetTextAircraftTailNumberByHex($input){

		//echo "</br> input tailNumber-". $input; //DEBUG
		if ($input == ''){
			return '';
		}		
		
		$hexTail = dechex($input);
		//echo " hexTail-" .$hexTail; //DEBUG
		 
		$str='';
		for ($i=0; $i < strlen($hexTail)-1; $i+=2)
		{
			$str .= chr(hexdec($hexTail[$i].$hexTail[$i+1]));
		}
		
		//echo " tailnumber string-" .$str; //DEBUG

		return strrev($str);;
	}
	 
} // TaxibotMission
