<?php
require 'lib/model/om/BaseTaxibotLog.php';

/**
 * Skeleton subclass for representing a row from the 'taxibot_log' table.
 *
 * TaxibotLog
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue May 7 10:25:46 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements. This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package lib.model
 */
class TaxibotLog extends BaseTaxibotLog {
} // TaxibotLog
