<?php

require 'lib/model/om/BaseTaxibotFailure.php';


/**
 * Skeleton subclass for representing a row from the 'taxibot_failure' table.
 *
 * TaxibotFailure
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sun Feb  2 18:00:11 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class TaxibotFailure extends BaseTaxibotFailure {

} // TaxibotFailure
