<?php
require 'lib/model/om/BaseTaxibotStack.php';

/**
 * Skeleton subclass for representing a row from the 'taxibot_stack' table.
 *
 * TaxibotStack
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed May 29 15:50:52 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements. This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package lib.model
 */
class TaxibotStack extends BaseTaxibotStack {
} // TaxibotStack
