<?php

require 'lib/model/om/BaseTaxibotCancel.php';


/**
 * Skeleton subclass for representing a row from the 'taxibot_cancel' table.
 *
 * TaxibotCancel
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Feb 17 08:33:23 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class TaxibotCancel extends BaseTaxibotCancel {

} // TaxibotCancel
