<?php

require 'lib/model/om/BaseTaxibotAlert.php';


/**
 * Skeleton subclass for representing a row from the 'taxibot_alert' table.
 *
 * TaxibotAlert
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Feb 10 06:33:29 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class TaxibotAlert extends BaseTaxibotAlert {

} // TaxibotAlert
