<?php
require 'lib/model/om/BaseTaxibotTowingTimestamp.php';

/**
 * Skeleton subclass for representing a row from the 'taxibot_towing_timestamp' table.
 *
 * All additional timestamps for taxibots.
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Feb 8 10:28:39 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements. This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package lib.model
 */
class TaxibotTowingTimestamp extends BaseTaxibotTowingTimestamp {
} // TaxibotTowingTimestamp
