<?php
require 'lib/model/om/BaseTaxibotHasInterruptionCausePeer.php';

/**
 * Skeleton subclass for performing query and update operations on the 'taxibot_has_interruption_cause' table.
 *
 * Assignment of interruptions to activities.
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 02/14/13 10:54:18
 *
 * You should add additional methods to this class to meet the
 * application requirements. This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package lib.model
 */
class TaxibotHasInterruptionCausePeer extends BaseTaxibotHasInterruptionCausePeer {
	
	/**
	 * Returns the suitable interruption for tractor, username and flightnumber (and date)
	 *
	 * @author Karsten
	 * @param String $username        	
	 * @param String $tractor        	
	 * @param String $start        	
	 */
	public static function getInterruption($timestamp_id, $interruption_cause_id, $start, $date = null) {
		$criteria = new Criteria ();
		$criteria->add ( TaxibotHasInterruptionCausePeer::TAXIBOT_TOWING_TIMESTAMP_ID, $timestamp_id );
		$criteria->addAnd ( TaxibotHasInterruptionCausePeer::TAXIBOT_TOWING_TIMESTAMP_INTERRUPTION_CAUSE_ID, $interruption_cause_id );
		$criteria->addAnd ( TaxibotHasInterruptionCausePeer::START, $start );
		$interruption = TaxibotHasInterruptionCausePeer::doSelectOne ( $criteria );
		return $interruption;
	}
} // TaxibotHasInterruptionCausePeer
