<?php
require 'lib/model/om/BaseTaxibotTable.php';

/**
 * Skeleton subclass for representing a row from the 'taxibot_table' table.
 *
 * TaxibotTable
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Thu May 23 11:41:14 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements. This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package lib.model
 */
class TaxibotTable extends BaseTaxibotTable {
} // TaxibotTable
