<?php
require 'lib/model/om/BaseTaxibotInterruptionCause.php';

/**
 * Skeleton subclass for representing a row from the 'taxibot_interruption_cause' table.
 *
 * Possible interruption causes for taxibot activites.
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Mar 5 10:07:09 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements. This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package lib.model
 */
class TaxibotInterruptionCause extends BaseTaxibotInterruptionCause {
} // TaxibotInterruptionCause
