<?php

require 'lib/model/om/BaseTaxibotCancelPeer.php';


/**
 * Skeleton subclass for performing query and update operations on the 'taxibot_cancel' table.
 *
 * TaxibotCancel
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Mon Feb 17 08:33:23 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class TaxibotCancelPeer extends BaseTaxibotCancelPeer {
	static public function GetLastCancel() {
		$items = self::doSelect ( new Criteria () );
		$count = count($items);
		
		if ($count == 0)
			return null;
		
		return $items[$count- 1];
	}
} // TaxibotCancelPeer
