<?php

require 'lib/model/om/BaseTaxibotPartsMission.php';


/**
 * Skeleton subclass for representing a row from the 'taxibot_parts_mission' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sat Nov  8 22:37:25 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class TaxibotPartsMission extends BaseTaxibotPartsMission {
} // TaxibotPartsMission
