<?php

require 'lib/model/om/BaseTaxibotVector.php';


/**
 * Skeleton subclass for representing a row from the 'taxibot_vector' table.
 *
 * TaxibotVector
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Feb  5 10:08:57 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class TaxibotVector extends BaseTaxibotVector {

} // TaxibotVector
