<?php

require 'lib/model/om/BaseTaxibotFatigueHistory.php';


/**
 * Skeleton subclass for representing a row from the 'taxibot_fatigue_history' table.
 *
 * TaxibotFatigueHistory
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Tue Nov  4 09:14:33 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class TaxibotFatigueHistory extends BaseTaxibotFatigueHistory {

} // TaxibotFatigueHistory
