<?php
require 'lib/model/om/BaseTaxibotExceedEvent.php';

/**
 * Skeleton subclass for representing a row from the 'taxibot_exceed_event' table.
 *
 * TaxibotExceedEvent
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Wed Sep 11 13:13:07 2013
 *
 * You should add additional methods to this class to meet the
 * application requirements. This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package lib.model
 */
class TaxibotExceedEvent extends BaseTaxibotExceedEvent {
} // TaxibotExceedEvent
