<?php

require 'lib/model/om/BaseTowingActivity.php';


/**
 * Skeleton subclass for representing a row from the 'towing_activity' table.
 *
 * Table for a client to read or write data.
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Sun Feb 16 11:19:13 2014
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class TowingActivity extends BaseTowingActivity {

} // TowingActivity
